version: "3.7"
services:

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pastebeandb
    networks:
      - pastebean-net

  flyway:
    image: flyway/flyway:latest
    volumes:
      - ./db/migrations:/flyway/sql
      - ./db/flyway-conf:/flyway/conf
    networks:
      - pastebean-net
    command: ["migrate"]
    depends_on:
      - "postgres"

  envoy_proxy:
    image: envoyproxy/envoy:v1.23-latest
    volumes:
    - ./envoy-config.yaml:/etc/envoy.yaml
    networks:
    - pastebean-net
    command: ["envoy", "-c", "/etc/envoy.yaml"]
    ports:
    - "8000:8000"
    - "8001:8001"

  create_service:
    image: delusionaloptimist/pastebean-create:latest
    networks:
      - pastebean-net
    environment:
      POSTGRES_PASSWORD: password
      PORT: 8080
    depends_on:
      - "postgres"

  read_service:
    image: delusionaloptimist/pastebean-read:latest
    networks:
      - pastebean-net
    environment:
      POSTGRES_PASSWORD: password
      PORT: 8080
    depends_on:
      - "postgres"

  update_service:
    image: delusionaloptimist/pastebean-update:latest
    networks:
      - pastebean-net
    environment:
      POSTGRES_PASSWORD: password
      PORT: 8080
    depends_on:
      - "postgres"

  delete_service:
    image: delusionaloptimist/pastebean-delete:latest
    networks:
      - pastebean-net
    environment:
      POSTGRES_PASSWORD: password
      PORT: 8080
    depends_on:
      - "postgres"

  web_server:
    image: busybox
    networks:
      - pastebean-net
    volumes:
      - ./web:/web
    command: ["httpd", "-h", "/web"]

networks:
  pastebean-net: {}
